### ISSUE TITLE
Time does not match on the Charts and Server pages.

### ISSUE THREAD

**Issue by hamilton5** [loadavg/loadavg#17]
Charts:
<b>Today</b> - Sunday, Nov. 30 17:58 pm  
Server:
Server Data  18:04:08 up 4 days, 18:15, 1 user, load average: 0.07, 0.04, 0.05

There is a difference in time on the two pages. I understand the Charts page is probably local time, but I think the time should show the last time that charts were updated like v1.5 did, or at least the server time. Also the time is in 24hour format but still shows the am/pm.

**Comment by loadavg** [comment]
cleaned up a bit for the 2.1 release though needs to be properly reviewed again, you are so right :)
