### ISSUE TITLE
Auto-login redirects to root folder

### ISSUE THREAD

**Issue by ShiroiKuma** [loadavg/loadavg#25]
I've got this setup on my nginx server in a sub folder of the main htdocs. So my url is http://RPi01/loadavg/

Upon logging in I'm redirected to http://RPi01/index.php, so I tried again, and then to http://RPi01/loadavg/public/index.php too... and I get redirected again.

Looking at the code I saw this:

````if (  (!isset($_SESSION['logged_in']) || ($_SESSION['logged_in'] == false)) && ($banned == false) )
{
        //if cookies are here and match log them in
        if ($loadavg->checkCookies()) {
                $_SESSION['logged_in'] = true;
            header("Location: /index.php");
        }
}````

So I'm forced to have this app in the root directory of a subdomain?

The kb http://www.loadavg.com/kb/configuring-your-server/ says you can have it under your domain as a sub-folder without any issues though.

**Comment by ShiroiKuma** [comment]
Nevermind, this ended up being php-fpm sessions conflicts on my own server :(

**Comment by jmblum** [comment]
I have this issue now. I know this issue has been closed, but any advice? Should I open a new issue or has anyone else experienced this? I don't know anything about php-fpm sessions but as I have the issue on two different servers (one VPS, one shared) I don't think that is the case.
