### ISSUE TITLE
hostname -d

### ISSUE THREAD

**Issue by CanisHelix** [loadavg/loadavg#26]
hostname -d returns the domainname
hostname alone would return the hostname

Yet on the server page, you're displaying "Hostname" as being "hostname -d" ... perhaps that should be renamed to domainname instead on the server page?

**Comment by loadavg** [comment]
Good point and thanks for bringing it up ! We will clean up the server page a bit to be more concise as you have pointed out!

**Comment by ShiroiKuma** [comment]
A few other issues, such as "uname -p" for the processor type not being standard on all distributions. But I want to double check if it's just unable to detect BCM2085's yet, it might be correct that it's "Unknown Processor", but I'd feel better looking into more first before suggesting something else.

On a side note, love this monitoring tool. It's the only one I've found so far that doesn't kill a RaspberryPi B+. Other's I've tried ended up forcing the CPU to 100% half the time.

A nice feature though, on the memory module would be to be able to see a breakdown on the usage. i.e. "Oh, 6hrs ago memory and swap were maxed out! What process(s) did that?" Perhaps similar for the CPU/Process Module too could be a handy feature.

**Comment by loadavg** [comment]
Great news :) let me know please so i can address it.  i just ordered a Pi 2 as well - quad core cant wait for it to arrive to test on... i have a pi 1 that i test on here to keep the load down but it keeps dieing on me and freezing up so gave up on it.

the latest 2.2 in git (just pushed now) has a process module and an alerts module - if you turn them on via the plugins settings then they give you some of this funcationality... 

the process module lets you click on the chart to see what processess were running at that point in time (but the logging of this data starts at the point of upgrade so you can only access new data)

the alerts module is very basic at this point but will be built out - it gives you a breakdown of alerts per module for now.

havent really tuned them all to be as streamlined as possible yet will do that for the final 2.2 release

we will be porting to node.js at some point to get rid of the reliance on php+apache. that being said, php+nginx work well as a light monitoring solution for me

**Comment by loadavg** [comment]
interesting point - we can configure the process tool to use any module for looking up process usage as we get the time from the chart and look it up in the process logs. default is cpu load module but we can make this user definable really...
