### ISSUE TITLE
Notice: Undefined offset:

### ISSUE THREAD

**Issue by Xtreme89** [loadavg/loadavg#27]
Hi,
I have the following message in the tab Process

Notice: Undefined offset: 6 in /load/lib/plugins/Process/Process.php on line 96

Notice: Undefined index: %cpu in /load/lib/plugins/Process/Process.php on line 133

**Comment by loadavg** [comment]
Yes - we are aware of this issue. It has been fixed in the 2.2 branch which will be released shortly!

You can access 2.2 using the instructions here:

http://www.loadavg.com/develop/

Please try it out if you can ! and let me know if it works better...

**Comment by Xtreme89** [comment]
HI, 

I have install the develop version 2.2 and it works now.

No error message until now.
