### ISSUE TITLE
font color

### ISSUE THREAD

**Issue by Xtreme89** [loadavg/loadavg#28]
The font color for the text input is very difficult to read. I think it is lightgrey? White background with lightgray font-color is not so nice

**Comment by loadavg** [comment]
yes we had a few requests to clean it up along with the labels on the charts which are also hard to read - thanks for the reminder - will post a pic here

**Comment by loadavg** [comment]
made it a bit darker in the 2.2 branch - from #A7A7A7 to  #787878 looks a bit better now.
