### ISSUE TITLE
scrolling on a mobile device is painful.

### ISSUE THREAD

**Issue by hamilton5** [loadavg/loadavg#29]
it's horrible with these charts that are movable. have you tried it?
android 4.4 / chrome 40 / 5" screen 1080i

**Comment by loadavg** [comment]
yes horrible! will disable it for mobile ASAP - need a mobile theme as well, going to look into this.

**Comment by loadavg** [comment]
checked in a patch to the 2.2 branch that disables the drag and drop, but need a cleaner solution really as we would like to keep the expand and collapse ability. currently you can still drag headers things just dont move around.

working on it!
